from random import randint

from fastapi import APIRouter, Header
from fastapi.encoders import jsonable_encoder
from starlette.responses import JSONResponse

from api_fastapi.models.darwin import InputDarwin, OutputDarwin
from api_fastapi.models.darwin import InputAPI, OutputAPI
from api_fastapi.models.darwin import input_darwin_example, input_api_example


router = APIRouter()


@router.post("/ping", tags=["General test with Darwin interface"], response_model=OutputDarwin)
def ping(body: InputDarwin = input_darwin_example):
    print("/ping POST: {}".format(body.CorrelationId))

    base_amount = float(randint(100, 500))
    amount = base_amount * body.FirstCar.CarRisk * body.FirstDriver.BonusMalus
    amount2 = amount * randint(1, 3)

    return OutputDarwin(**{
        "CorrelationId": body.CorrelationId,
        "Coverages": [
            {
                "GrossAmount": amount,
                "NetAmount": amount * 0.614,
                "Type": "TPL"
            },
            {
                "GrossAmount": amount2,
                "NetAmount": amount2 * 0.614,
                "Type": "GlassBreakage"
            }
        ],
        "Formulas": [
            {
                "Name": "DAFC",
                "Packs": [
                    {
                        "Name": "None",
                        "Periods": [
                            {
                                "Name": "Monthly",
                                "PremiumInclTaxes": amount,
                                "PremiumLoaded": amount * 1.2
                            },
                            {
                                "Name": "Yearly",
                                "PremiumInclTaxes": amount * 12,
                                "PremiumLoaded": amount * 12 * 1.2
                            }
                        ]
                    },
                    {
                        "Name": "Protection",
                        "Periods": [
                            {
                                "Name": "Monthly",
                                "PremiumInclTaxes": amount * 1.1,
                                "PremiumLoaded": amount * 1.1 * 1.2
                            },
                            {
                                "Name": "Yearly",
                                "PremiumInclTaxes": amount * 1.1 * 12,
                                "PremiumLoaded": amount * 1.1 * 12 * 1.2
                            }
                        ]
                    }
                ]
            },
            {
                "Name": "DATPL",
                "Packs": [
                    {
                        "Name": "None",
                        "Periods": [
                            {
                                "Name": "Monthly",
                                "PremiumInclTaxes": amount * 1.1412,
                                "PremiumLoaded": amount * 1.1412 * 1.2
                            },
                            {
                                "Name": "Yearly",
                                "PremiumInclTaxes": amount * 1.1412 * 12,
                                "PremiumLoaded": amount * 1.1412 * 12 * 1.2
                            }
                        ]
                    },
                    {
                        "Name": "Protection",
                        "Periods": [
                            {
                                "Name": "Monthly",
                                "PremiumInclTaxes": amount * 1.1412 * 1.1,
                                "PremiumLoaded": amount * 1.1412 * 1.1 * 1.2
                            },
                            {
                                "Name": "Yearly",
                                "PremiumInclTaxes": amount * 1.1412 * 1.1 * 12,
                                "PremiumLoaded": amount * 1.1412 * 1.1 * 1.2 * 12
                            }
                        ]
                    }
                ]
            }
        ]
    })


@router.post("/pingAPI", tags=["General test of API with Darwin interface"], response_model=OutputAPI)
def ping_api(body: InputAPI = input_api_example):
    print("/ping API POST: {}".format(body.CorrelationId))
    attributes = [
        {'Name': 'CoverInfo.CrossedPremiumInctaxes', 'Current': '193.84'},
        {'Name': 'CoverInfo.CurentPackageEligible', 'Current': '1'},
        {'Name': 'CoverInfo.DAFCPremiumIncOptionsInclTaxes', 'Current': '39996.0'},
        {'Name': 'CoverInfo.DATPLGlassPremiumIncOptionsInclTaxes', 'Current': '19998.0'},
        {'Name': 'CoverInfo.DATPLPremiumIncOptionsInclTaxes', 'Current': '9999.0'},
        {'Name': 'CoverInfo.DATPLTheftPremiumIncOptionsInclTaxes', 'Current': '29997.0'},
        {'Name': 'CoverInfo.GFTheoFactor1', 'Current': '0.0'},
        {'Name': 'CoverInfo.GFTheoFactor2', 'Current': '0.0'},
        {'Name': 'CoverInfo.GFTheoFactor3', 'Current': '0.0'},
        {'Name': 'CoverInfo.GFTheoFactor4', 'Current': '0.0'},
        {'Name': 'CoverInfo.HalfYearlyPremium1InclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo.HalfYearlyPremium2InclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo.IsDAFCPackageEligible', 'Current': '1'},
        {'Name': 'CoverInfo.IsDATPLAdvancedPackageEligible', 'Current': '1'},
        {'Name': 'CoverInfo.IsDATPLGlassPackageEligible', 'Current': '1'},
        {'Name': 'CoverInfo.IsDATPLPackageEligibile', 'Current': '1'},
        {'Name': 'CoverInfo.PremiumBeforeRenewalIncOptionsInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo.PremiumBeforeRenewalIncOptionsNetOfTax', 'Current': '0.0'},
        {'Name': 'CoverInfo.PremiumIncOptionsInclTaxes', 'Current': '287.15'},
        {'Name': 'CoverInfo.PremiumIncOptionsInclTaxesChange', 'Current': '36.66'},
        {'Name': 'CoverInfo.PremiumIncOptionsNetOfTax', 'Current': '232.54'},
        {'Name': 'CoverInfo.PremiumIncOptionsTaxes', 'Current': '54.61'},
        {'Name': 'CoverInfo.PremiumLo].PremiumMonthlyInclTaxesadedIncOptions', 'Current': '219.09'},
        {'Name': 'CoverInfo.PremiumMonthlyIncOptionsInclTaxes', 'Current': '23.92'},
        {'Name': 'CoverInfo.PremiumMonthlyIncOptionsNetOfTax', 'Current': '19.37'},
        {'Name': 'CoverInfo.PremiumNotUnderBonusMalusIncOptionsIncTaxes', 'Current': '128.37'},
        {'Name': 'CoverInfo.PremiumNotUnderBonusMalusIncOptionsNetOfTaxes', 'Current': '113.46'},
        {'Name': 'CoverInfo.PremiumNotUsingGlobalFactorIncTaxes', 'Current': '143.01'},
        {'Name': 'CoverInfo.PremiumPackageInclTaxes', 'Current': '193.84'},
        {'Name': 'CoverInfo.PremiumPackageMonthlyInclTaxes', 'Current': '16.15'},
        {'Name': 'CoverInfo.PremiumPackageNetOfTax', 'Current': '150.47'},
        {'Name': 'CoverInfo.PremiumReferenceAfterBonusMalusInclTaxes', 'Current': '109.08'},
        {'Name': 'CoverInfo.PremiumReferenceAfterBonusMalusNetOfTax', 'Current': '84.1'},
        {'Name': 'CoverInfo.PremiumReferenceInclTaxes', 'Current': '218.16'},
        {'Name': 'CoverInfo.PremiumReferenceNetOfTax', 'Current': '168.2'},
        {'Name': 'CoverInfo.PremiumRiskIncOptions', 'Current': '154.53'},
        {'Name': 'CoverInfo.PremiumUsingGlobalFactorIncTaxes', 'Current': '144.14'},
        {'Name': 'CoverInfo.SelectedPackageTaxes', 'Current': '150.47'},
        {'Name': 'CoverInfo.TargetPremiumCoeff', 'Current': '1.0'},
        {'Name': 'CoverInfo[CourtesyCar].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[CourtesyCar].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[CourtesyCar].PremiumInclTaxes', 'Current': '18.0'},
        {'Name': 'CoverInfo[CourtesyCar].PremiumLoaded', 'Current': '5.0'},
        {'Name': 'CoverInfo[CourtesyCar].PremiumMarket', 'Current': '15.0'},
        {'Name': 'CoverInfo[CourtesyCar].PremiumMonthlyInclTaxes', 'Current': '1.5'},
        {'Name': 'CoverInfo[CourtesyCar].PremiumRisk', 'Current': '5.0'},
        {'Name': 'CoverInfo[CourtesyCar].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[CourtesyCar].Tax[VAT].Amount', 'Current': '3.0'},
        {'Name': 'CoverInfo[CourtesyCarPartRoadsideAssistanceBasic].PremiumMarket', 'Current': '15.0'},
        {'Name': 'CoverInfo[DeductibleUpgrade].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[DeductibleUpgrade].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[DeductibleUpgrade].PremiumInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgrade].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgrade].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgrade].PremiumMonthlyInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgrade].PremiumRisk', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgrade].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgradePartFireExplosion].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgradePartFireExplosion].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgradePartOwnDamage].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgradePartOwnDamage].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgradePartTheft].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[DeductibleUpgradePartTheft].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[DriverProtection].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[DriverProtection].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[DriverProtection].PremiumInclTaxes', 'Current': '25.89'},
        {'Name': 'CoverInfo[DriverProtection].PremiumIncOptionsInclTaxes', 'Current': '77.2'},
        {'Name': 'CoverInfo[DriverProtection].PremiumLoaded', 'Current': '4.2'},
        {'Name': 'CoverInfo[DriverProtection].PremiumMarket', 'Current': '23.75'},
        {'Name': 'CoverInfo[DriverProtection].PremiumMarketIncOptions', 'Current': '70.82'},
        {'Name': 'CoverInfo[DriverProtection].PremiumMonthlyInclTaxes', 'Current': '2.15'},
        {'Name': 'CoverInfo[DriverProtection].PremiumRisk', 'Current': '2.52'},
        {'Name': 'CoverInfo[DriverProtection].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[DriverProtection].Tax[TCAP].Amount', 'Current': '2.14'},
        {'Name': 'CoverInfo[DriverProtection].TaxGlobalRate', 'Current': '0.09'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].PremiumInclTaxes', 'Current': '51.31'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].PremiumLoaded', 'Current': '5.09'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].PremiumMarket', 'Current': '47.07'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].PremiumMonthlyInclTaxes', 'Current': '4.27'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].PremiumRisk', 'Current': '5.09'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].SelectedLevel', 'Current': '2.0'},
        {'Name': 'CoverInfo[DriverProtectionUpgrade].Tax[TCAP].Amount', 'Current': '4.24'},
        {'Name': 'CoverInfo[DriverProtectionUpgradePartDriverProtection].PremiumMarket', 'Current': '47.07'},
        {'Name': 'CoverInfo[FireExplosion].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[FireExplosion].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[FireExplosion].PremiumInclTaxes', 'Current': '1.13'},
        {'Name': 'CoverInfo[FireExplosion].PremiumIncOptionsInclTaxes', 'Current': '1.13'},
        {'Name': 'CoverInfo[FireExplosion].PremiumLoaded', 'Current': '0.38'},
        {'Name': 'CoverInfo[FireExplosion].PremiumMarket', 'Current': '0.95'},
        {'Name': 'CoverInfo[FireExplosion].PremiumMarketIncOptions', 'Current': '0.95'},
        {'Name': 'CoverInfo[FireExplosion].PremiumMonthlyInclTaxes', 'Current': '0.09'},
        {'Name': 'CoverInfo[FireExplosion].PremiumRisk', 'Current': '0.36'},
        {'Name': 'CoverInfo[FireExplosion].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[FireExplosion].Tax[TCAA].Amount', 'Current': '0.18'},
        {'Name': 'CoverInfo[FireExplosion].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[Glass].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[Glass].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[Glass].PremiumInclTaxes', 'Current': '6.32'},
        {'Name': 'CoverInfo[Glass].PremiumIncOptionsInclTaxes', 'Current': '6.32'},
        {'Name': 'CoverInfo[Glass].PremiumLoaded', 'Current': '7.82'},
        {'Name': 'CoverInfo[Glass].PremiumMarket', 'Current': '5.35'},
        {'Name': 'CoverInfo[Glass].PremiumMarketIncOptions', 'Current': '5.35'},
        {'Name': 'CoverInfo[Glass].PremiumMonthlyInclTaxes', 'Current': '0.52'},
        {'Name': 'CoverInfo[Glass].PremiumRisk', 'Current': '7.71'},
        {'Name': 'CoverInfo[Glass].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[Glass].Tax[TCAA].Amount', 'Current': '0.97'},
        {'Name': 'CoverInfo[Glass].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[GroupFireExplosionTheft].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[GroupFireExplosionTheft].PremiumInclTaxes', 'Current': '2.26'},
        {'Name': 'CoverInfo[GroupFireExplosionTheft].PremiumMarket', 'Current': '1.9'},
        {'Name': 'CoverInfo[GroupFireExplosionTheft].PremiumMonthlyInclTaxes', 'Current': '0.18'},
        {'Name': 'CoverInfo[GroupFireExplosionTheft].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[GroupProtection].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[GroupProtection].PremiumInclTaxes', 'Current': '46.8'},
        {'Name': 'CoverInfo[GroupProtection].PremiumMarket', 'Current': '42.93'},
        {'Name': 'CoverInfo[GroupProtection].PremiumMonthlyInclTaxes', 'Current': '3.9'},
        {'Name': 'CoverInfo[GroupSerenity].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[GroupSerenity].PremiumInclTaxes', 'Current': '93.31'},
        {'Name': 'CoverInfo[GroupSerenity].PremiumMarket', 'Current': '82.07'},
        {'Name': 'CoverInfo[GroupSerenity].PremiumMonthlyInclTaxes', 'Current': '7.78'},
        {'Name': 'CoverInfo[GroupTerrorNaturalTech].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[GroupTerrorNaturalTech].PremiumInclTaxes', 'Current': '6.03'},
        {'Name': 'CoverInfo[GroupTerrorNaturalTech].PremiumMarket', 'Current': '0.11'},
        {'Name': 'CoverInfo[GroupTerrorNaturalTech].PremiumMonthlyInclTaxes', 'Current': '0.5'},
        {'Name': 'CoverInfo[GroupTerrorNaturalTech].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[GroupTPL].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[GroupTPL].PremiumInclTaxes', 'Current': '81.69'},
        {'Name': 'CoverInfo[GroupTPL].PremiumMarket', 'Current': '60.49'},
        {'Name': 'CoverInfo[GroupTPL].PremiumMonthlyInclTaxes', 'Current': '6.8'},
        {'Name': 'CoverInfo[GroupTPL].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[GroupTranquility].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[GroupTranquility].PremiumInclTaxes', 'Current': '69.31'},
        {'Name': 'CoverInfo[GroupTranquility].PremiumMarket', 'Current': '62.07'},
        {'Name': 'CoverInfo[GroupTranquility].PremiumMonthlyInclTaxes', 'Current': '5.78'},
        {'Name': 'CoverInfo[HandlingCosts].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumInclTaxes', 'Current': '43.8'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumLoaded', 'Current': '34.1'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket', 'Current': '34.98'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket[CFG_TPL].Amount', 'Current': '19.63'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket[CSS_TPL].Amount', 'Current': '19.63'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket[TCAA].Amount', 'Current': '5.7'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket[TCAA_TPL].Amount', 'Current': '19.63'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket[TCAP].Amount', 'Current': '9.35'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMarket[TCAP_LP].Amount', 'Current': '0.3'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumMonthlyInclTaxes', 'Current': '3.65'},
        {'Name': 'CoverInfo[HandlingCosts].PremiumRisk', 'Current': '34.1'},
        {'Name': 'CoverInfo[HandlingCosts].Tax[CFG_TPL].Amount', 'Current': '0.4'},
        {'Name': 'CoverInfo[HandlingCosts].Tax[CSS_TPL].Amount', 'Current': '2.95'},
        {'Name': 'CoverInfo[HandlingCosts].Tax[TCAA].Amount', 'Current': '1.03'},
        {'Name': 'CoverInfo[HandlingCosts].Tax[TCAA_TPL].Amount', 'Current': '3.54'},
        {'Name': 'CoverInfo[HandlingCosts].Tax[TCAP].Amount', 'Current': '0.85'},
        {'Name': 'CoverInfo[HandlingCosts].Tax[TCAP_LP].Amount', 'Current': '0.05'},
        {'Name': 'CoverInfo[HandlingCosts].TaxGlobalRate', 'Current': '0.2522'},
        {'Name': 'CoverInfo[LegalProtection].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[LegalProtection].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[LegalProtection].PremiumInclTaxes', 'Current': '1.08'},
        {'Name': 'CoverInfo[LegalProtection].PremiumIncOptionsInclTaxes', 'Current': '1.08'},
        {'Name': 'CoverInfo[LegalProtection].PremiumLoaded', 'Current': '0.44'},
        {'Name': 'CoverInfo[LegalProtection].PremiumMarket', 'Current': '0.95'},
        {'Name': 'CoverInfo[LegalProtection].PremiumMarketIncOptions', 'Current': '0.95'},
        {'Name': 'CoverInfo[LegalProtection].PremiumMonthlyInclTaxes', 'Current': '0.09'},
        {'Name': 'CoverInfo[LegalProtection].PremiumRisk', 'Current': '0.44'},
        {'Name': 'CoverInfo[LegalProtection].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[LegalProtection].Tax[TCAP_LP].Amount', 'Current': '0.13'},
        {'Name': 'CoverInfo[LegalProtection].TaxGlobalRate', 'Current': '0.134'},
        {'Name': 'CoverInfo[LoanOption].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[LoanOption].IsSelected', 'Current': '0'},
        {'Name': 'CoverInfo[LoanOption].PremiumInclTaxes', 'Current': '46.81'},
        {'Name': 'CoverInfo[LoanOption].PremiumLoaded', 'Current': '27.8571428571429'},
        {'Name': 'CoverInfo[LoanOption].PremiumMarket', 'Current': '39.00000000000006'},
        {'Name': 'CoverInfo[LoanOption].PremiumMonthlyInclTaxes', 'Current': '3.9'},
        {'Name': 'CoverInfo[LoanOption].PremiumRisk', 'Current': '27.8571428571429'},
        {'Name': 'CoverInfo[LoanOption].Tax[VAT].Amount', 'Current': '7.81'},
        {'Name': 'CoverInfo[LoanOptionPartRoadsideAssistanceBasic].PremiumMarket',
         'Current': '39.00000000000006'},
        {'Name': 'CoverInfo[Loyalty].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[Loyalty].IsSelected', 'Current': '0'},
        {'Name': 'CoverInfo[Loyalty].PremiumInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[Loyalty].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'CoverInfo[Loyalty].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[Loyalty].PremiumMonthlyInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[Loyalty].PremiumRisk', 'Current': '0.0'},
        {'Name': 'CoverInfo[Loyalty].SelectedLevel', 'Current': '0'},
        {'Name': 'CoverInfo[Loyalty].Tax[VAT].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[LoyaltyPartRoadsideAssistanceBasic].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[NaturalCatastrophy].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[NaturalCatastrophy].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumInclTaxes', 'Current': '0.13'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumIncOptionsInclTaxes', 'Current': '0.13'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumLoaded', 'Current': '0.06'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumMarket', 'Current': '0.11'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumMarketIncOptions', 'Current': '0.11'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumMonthlyInclTaxes', 'Current': '0.01'},
        {'Name': 'CoverInfo[NaturalCatastrophy].PremiumRisk', 'Current': '0.06'},
        {'Name': 'CoverInfo[NaturalCatastrophy].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[NaturalCatastrophy].Tax[TCAA].Amount', 'Current': '0.02'},
        {'Name': 'CoverInfo[NaturalCatastrophy].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[Nature].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[Nature].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[Nature].PremiumInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].PremiumIncOptionsInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].PremiumMarketIncOptions', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].PremiumMonthlyInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].PremiumRisk', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[Nature].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[Nature].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[OwnDamage].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[OwnDamage].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[OwnDamage].PremiumInclTaxes', 'Current': '12.05'},
        {'Name': 'CoverInfo[OwnDamage].PremiumIncOptionsInclTaxes', 'Current': '12.05'},
        {'Name': 'CoverInfo[OwnDamage].PremiumLoaded', 'Current': '10.97'},
        {'Name': 'CoverInfo[OwnDamage].PremiumMarket', 'Current': '10.21'},
        {'Name': 'CoverInfo[OwnDamage].PremiumMarketIncOptions', 'Current': '10.21'},
        {'Name': 'CoverInfo[OwnDamage].PremiumMonthlyInclTaxes', 'Current': '1.0'},
        {'Name': 'CoverInfo[OwnDamage].PremiumRisk', 'Current': '10.33'},
        {'Name': 'CoverInfo[OwnDamage].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[OwnDamage].Tax[TCAA].Amount', 'Current': '1.84'},
        {'Name': 'CoverInfo[OwnDamage].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[Recovery].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[Recovery].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[Recovery].PremiumInclTaxes', 'Current': '5.55'},
        {'Name': 'CoverInfo[Recovery].PremiumIncOptionsInclTaxes', 'Current': '5.55'},
        {'Name': 'CoverInfo[Recovery].PremiumLoaded', 'Current': '3.08'},
        {'Name': 'CoverInfo[Recovery].PremiumMarket', 'Current': '5.09'},
        {'Name': 'CoverInfo[Recovery].PremiumMarketIncOptions', 'Current': '5.09'},
        {'Name': 'CoverInfo[Recovery].PremiumMonthlyInclTaxes', 'Current': '0.46'},
        {'Name': 'CoverInfo[Recovery].PremiumRisk', 'Current': '-2.7'},
        {'Name': 'CoverInfo[Recovery].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[Recovery].Tax[TCAP].Amount', 'Current': '0.46'},
        {'Name': 'CoverInfo[Recovery].TaxGlobalRate', 'Current': '0.09'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumInclTaxes', 'Current': '9.17'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumIncOptionsInclTaxes', 'Current': '51.17'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumLoaded', 'Current': '11.17'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumMarket', 'Current': '7.64'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumMarketIncOptions', 'Current': '42.64'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumMonthlyInclTaxes', 'Current': '0.76'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].PremiumRisk', 'Current': '5.4'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].Tax[VAT].Amount', 'Current': '1.53'},
        {'Name': 'CoverInfo[RoadsideAssistanceBasic].TaxGlobalRate', 'Current': '0.38'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].PremiumInclTaxes', 'Current': '24.0'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].PremiumLoaded', 'Current': '12.79'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].PremiumMarket', 'Current': '20.0'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].PremiumMonthlyInclTaxes', 'Current': '2.0'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].PremiumRisk', 'Current': '12.79'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgrade].Tax[VAT].Amount', 'Current': '4.0'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgradePartRoadsideAssistanceBasic].PremiumMarket',
         'Current': '20.0'},
        {'Name': 'CoverInfo[RoadsideAssistanceUpgradePartRoadsideAssistanceBasic].Tax[VAT].Amount',
         'Current': '4.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumIncOptionsInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumMarketIncOptions', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumMonthlyInclTaxes', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].PremiumRisk', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'CoverInfo[TechnicalCatastrophy].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[TerroristAttack].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[TerroristAttack].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[TerroristAttack].PremiumInclTaxes', 'Current': '5.9'},
        {'Name': 'CoverInfo[TerroristAttack].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'CoverInfo[TerroristAttack].PremiumMarket', 'Current': '0.0'},
        {'Name': 'CoverInfo[TerroristAttack].PremiumMonthlyInclTaxes', 'Current': '0.49'},
        {'Name': 'CoverInfo[TerroristAttack].PremiumRisk', 'Current': '0.0'},
        {'Name': 'CoverInfo[TerroristAttack].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[TerroristAttack].Tax[TA].Amount', 'Current': '5.9'},
        {'Name': 'CoverInfo[Theft].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[Theft].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[Theft].PremiumInclTaxes', 'Current': '1.13'},
        {'Name': 'CoverInfo[Theft].PremiumIncOptionsInclTaxes', 'Current': '1.13'},
        {'Name': 'CoverInfo[Theft].PremiumLoaded', 'Current': '0.69'},
        {'Name': 'CoverInfo[Theft].PremiumMarket', 'Current': '0.95'},
        {'Name': 'CoverInfo[Theft].PremiumMarketIncOptions', 'Current': '0.95'},
        {'Name': 'CoverInfo[Theft].PremiumMonthlyInclTaxes', 'Current': '0.09'},
        {'Name': 'CoverInfo[Theft].PremiumRisk', 'Current': '0.66'},
        {'Name': 'CoverInfo[Theft].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[Theft].Tax[TCAA].Amount', 'Current': '0.18'},
        {'Name': 'CoverInfo[Theft].TaxGlobalRate', 'Current': '0.18'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumInclTaxes', 'Current': '53.9'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumIncOptionsInclTaxes', 'Current': '53.9'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumLoaded', 'Current': '88.87'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumMarket', 'Current': '39.92'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumMarketIncOptions', 'Current': '39.92'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumMonthlyInclTaxes', 'Current': '4.49'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].PremiumRisk', 'Current': '56.15'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].Tax[CFG_TPL].Amount', 'Current': '0.8'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].Tax[CSS_TPL].Amount', 'Current': '5.99'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].Tax[TCAA_TPL].Amount', 'Current': '7.19'},
        {'Name': 'CoverInfo[TPLMandatoryBodyInjury].TaxGlobalRate', 'Current': '0.35'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].IsAvailable', 'Current': '1'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].IsSelected', 'Current': '1'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumInclTaxes', 'Current': '27.79'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumIncOptionsInclTaxes', 'Current': '27.79'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumLoaded', 'Current': '34.43'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumMarket', 'Current': '20.57'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumMarketIncOptions', 'Current': '20.57'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumMonthlyInclTaxes', 'Current': '2.31'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].PremiumRisk', 'Current': '16.62'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].SelectedLevel', 'Current': '1'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].Tax[CFG_TPL].Amount', 'Current': '0.42'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].Tax[CSS_TPL].Amount', 'Current': '3.09'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].Tax[TCAA_TPL].Amount', 'Current': '3.71'},
        {'Name': 'CoverInfo[TPLMandatoryMaterial].TaxGlobalRate', 'Current': '0.35'},
        {'Name': 'EndorsementFees.PremiumInclTaxes', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumInclTaxesIfNotOverruled', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket[CFG_TPL].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket[CSS_TPL].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket[TCAA_TPL].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket[TCAP].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.PremiumMarket[TCAP_LP].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.Tax[CFG_TPL].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.Tax[CSS_TPL].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.Tax[TCAA].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.Tax[TCAA_TPL].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.Tax[TCAP].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.Tax[TCAP_LP].Amount', 'Current': '0.0'},
        {'Name': 'EndorsementFees.TaxGlobalRate', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].PremiumInclTaxes', 'Current': '193.84'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '16.15'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].PremiumInclTaxes', 'Current': '189.94'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '15.82'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[None].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].PremiumInclTaxes', 'Current': '240.64'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '20.05'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].PremiumInclTaxes', 'Current': '236.74'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '19.72'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Protection].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].PremiumInclTaxes', 'Current': '287.15'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '23.92'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].PremiumInclTaxes', 'Current': '283.25'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '23.6'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Serenity].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].PremiumInclTaxes', 'Current': '263.15'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '21.92'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].PremiumInclTaxes', 'Current': '259.25'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '21.6'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DAFC].Pack[Tranquility].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].PremiumInclTaxes', 'Current': '167.65'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '13.97'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].PremiumInclTaxes', 'Current': '164.14'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '13.67'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[None].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].PremiumInclTaxes', 'Current': '214.45'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '17.87'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].PremiumInclTaxes', 'Current': '210.94'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '17.57'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Protection].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].PremiumInclTaxes', 'Current': '260.96'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '21.74'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].PremiumInclTaxes', 'Current': '257.45'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '21.45'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Serenity].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].PremiumInclTaxes', 'Current': '236.96'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '19.74'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].PremiumInclTaxes', 'Current': '233.45'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '19.45'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPL].Pack[Tranquility].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].PremiumInclTaxes', 'Current': '182.04'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '15.17'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].PremiumInclTaxes', 'Current': '178.5'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '14.87'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[None].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].HandlingCostsNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].PremiumInclTaxes',
         'Current': '228.84'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '19.07'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].HandlingCostsNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].PremiumInclTaxes', 'Current': '225.3'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].PremiumMonthlyInclTaxes ',
         'Current': '18.77'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Protection].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].HandlingCostsNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].PremiumInclTaxes', 'Current': '275.35'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '22.94'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].PremiumInclTaxes', 'Current': '271.81'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].PremiumMonthlyInclTaxes ',
         'Current': '22.65'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Serenity].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].HandlingCostsNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].PremiumInclTaxes',
         'Current': '251.35'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '20.94'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].HandlingCostsNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].PremiumInclTaxes',
         'Current': '247.81'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].PremiumMonthlyInclTaxes ',
         'Current': '20.65'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLAdvanced].Pack[Tranquility].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].PremiumInclTaxes', 'Current': '179.73'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].PremiumMonthlyInclTaxes ', 'Current': '14.97'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].PremiumInclTaxes', 'Current': '176.05'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].PremiumMonthlyInclTaxes ', 'Current': '14.67'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[None].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].PremiumInclTaxes', 'Current': '226.53'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '18.87'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].PremiumInclTaxes', 'Current': '222.85'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].PremiumMonthlyInclTaxes ',
         'Current': '18.57'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Protection].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].PremiumInclTaxes', 'Current': '273.04'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '22.75'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].HandlingCostsInclTaxes', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].PremiumInclTaxes', 'Current': '269.36'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].PremiumMonthlyInclTaxes ',
         'Current': '22.44'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].PremiumMonthlyNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Serenity].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].HandlingCostsNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].PremiumInclTaxes', 'Current': '249.04'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].PremiumMonthlyInclTaxes ',
         'Current': '20.75'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Monthly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].HandlingCostsInclTaxes',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].HandlingCostsNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].PremiumInclTaxes', 'Current': '245.36'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].PremiumLoaded', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].PremiumMonthlyInclTaxes ',
         'Current': '20.44'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].PremiumMonthlyNetOfTax',
         'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].PremiumNetOfTax', 'Current': '0.0'},
        {'Name': 'Formula[DATPLGlass].Pack[Tranquility].Period[Yearly].PremiumRisk', 'Current': '0.0'},
        {'Name': 'ObjectContract.AdditionalDeclared1Coefficient', 'Current': '1.0'},
        {'Name': 'ObjectContract.AdditionalDeclared2Coefficient', 'Current': '1.0'},
        {'Name': 'ObjectContract.AdditionalDeclaredDriversCoeff', 'Current': '1.0'},
        {'Name': 'ObjectContract.CarChangeFactor', 'Current': '0.0'},
        {'Name': 'Factor.Frequency', 'Current': '1.09'},
        {'Name': 'ObjectContract.GlobalFactor', 'Current': '1.0'},
        {'Name': 'ObjectContract.GreenOfferSelected', 'Current': '0'},
        {'Name': 'ObjectContract.GreenOffferCoefficient', 'Current': '1.0'},
        {'Name': 'ObjectContract.PremiumTaxTotal[CFG_TPL].Amount', 'Current': '1.22'},
        {'Name': 'ObjectContract.PremiumTaxTotal[CSS_TPL].Amount', 'Current': '9.08'},
        {'Name': 'ObjectContract.PremiumTaxTotal[TA].Amount', 'Current': '5.9'},
        {'Name': 'ObjectContract.PremiumTaxTotal[TCAA].Amount', 'Current': '3.19'},
        {'Name': 'ObjectContract.PremiumTaxTotal[TCAA_TPL].Amount', 'Current': '10.9'},
        {'Name': 'ObjectContract.PremiumTaxTotal[TCAP].Amount', 'Current': '2.6'},
        {'Name': 'ObjectContract.PremiumTaxTotal[VAT].Amount', 'Current': '8.53'},
        {'Name': 'ObjectContract.SubscriptionFactor', 'Current': '1.0'},
        {'Name': 'ObjectPolicyHolder.SubCancelationScore', 'Current': '-231088.0'},
        {'Name': 'ObjectPortfolioProtection.CloseTarifTheoreticalFactor', 'Current': '-1.0'},
        {'Name': 'ObjectPortfolioProtection.FactorOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.CapCalculated', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.Factor', 'Current': '1.0'},
        {'Name': 'ObjectRenewal.FloorCalculated', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.IntermediaryFactorOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.NewBusinessFactorAtRenewalOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumCap', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumFloor', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumIntermediaryInclTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumIntermediaryNetOfTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumNewBusinessInclTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumNewBusinessNetOfTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalAutInclTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalAutNetOfTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalBisAutInclTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalBisAutNetOfTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalBisInclTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalBisNetOfTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalInclTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectRenewal.PremiumTheoreticalNetOfTaxOut', 'Current': '0.0'},
        {'Name': 'ObjectThermometer.AlmostSubscriptionAmountOut', 'Current': '287.15'},
        {'Name': 'ObjectThermometer.LongLifeLast1GlobalFactorTheo', 'Current': '0.0'},
        {'Name': 'PremiumTotalMonthlyInclTax', 'Current': '0.0'},
        {'Name': 'PremiumTotalInclTaxForDisplay', 'Current': '0.0'}
    ]

    return OutputAPI(**{
        "CorrelationId": body.CorrelationId,
        "EngineVersion": "FR_TA_V1",
        "PreviousEngineVersion": "FR_TA_V1",
        "ProductInterfaceStorageId": body.ProductInterfaceStorageId,
        "Attributes": attributes
    })
